trigger: none

pool:
  # vmImage: 'ubuntu-latest'
  name: selfhosted

jobs:
- job: BuildAndTest
  displayName: "Build, Test, and Analyze"
  steps:

  - task: Maven@4
    displayName: 'Maven Compile'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean compile -Dcheckstyle.skip'

  - task: Maven@4
    displayName: 'Maven JUnit Tests'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test -Dcheckstyle.skip jacoco:report -Dmaven.test.failure.ignore=true'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/*.xml'
      failTaskOnFailedTests: true

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '**/target/site/jacoco/jacoco.xml'
      failIfCoverageEmpty: true

  - task: Maven@4
    displayName: 'Build Package'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install -Dcheckstyle.skip -DskipTests'
