trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'docker-hub-credentials'
  imageRepository: 'brainupgrade/spring-petclinic'
  containerImageTag: '$(Build.BuildId)'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: Docker@2
  displayName: 'Docker Build and Push'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: '**/Dockerfile'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: '$(containerImageTag)'

- task: Docker@2
  displayName: 'Tag and Push Latest'
  inputs:
    command: 'tagAndPush'
    repository: '$(imageRepository)'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: 'latest'
