trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers
pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

pool:
  # vmImage: 'ubuntu-latest'
  name: github

variables:
  dockerRegistryServiceConnection: 'docker-hub-credentials'
  imageRepository: 'brainupgrade/spring-petclinic'
  containerImageTag: '$(Build.BuildId)'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'

- task: Docker@2
  displayName: 'Docker Build and Push'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: '**/Dockerfile-multi'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: '$(containerImageTag),latest'
