trigger:
  branches:
    exclude:
      - '*'  # Prevent regular push triggers
pr:
  branches:
    exclude:
      - '*'  # Don't trigger on PRs

pool:
  vmImage: 'ubuntu-latest'
  # name: github

jobs:
- job: BuildAndTest
  displayName: "Build, Test, and Analyze"
  steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
      displayName: 'Set up JDK 17'

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'sonar-cloud'
        organization: 'brainupgrade-in'
        scannerMode: 'Other'
        projectKey: 'brainupgrade-in_spring-petclinic'
        projectName: 'spring-petclinic'
        extraProperties: |
          sonar.java.binaries=target/classes        
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-Dcheckstyle.skip -DskipTests -Dsonar.projectKey=brainupgrade-in_spring-petclinic'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
      displayName: 'Maven build with SonarCloud analysis'
    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'       
