trigger: none

pool:
  # vmImage: 'ubuntu-latest'
  name: selfhosted

jobs:
- job: BuildAndTest
  displayName: "Build, Test, and Analyze"
  steps:

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'sonar-cloud'
        organization: 'brainupgrade-in'
        scannerMode: 'other'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
      env:
        JAVA_HOME_17_X64: "/usr/lib/jvm/java-17-openjdk-amd64"
        PATH: "/usr/lib/jvm/java-17-openjdk-amd64/bin:$(PATH)"

    # Publish Quality Gate Result task
    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'       
